# Generated by Django 3.2.2 on 2021-10-30 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0002_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.IntegerField(default=99)),
                ('title', models.CharField(max_length=64)),
                ('text_percent', models.IntegerField(default=90)),
                ('hotspot_x', models.IntegerField(default=900)),
                ('hotspot_y', models.IntegerField(default=90)),
                ('hotspot_r', models.IntegerField(default=20)),
                ('blurb', models.TextField(blank=True, null=True)),
                ('more', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interactive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=48, unique=True, verbose_name='short name')),
                ('title', models.CharField(max_length=64)),
                ('blurb', models.TextField(blank=True, null=True, verbose_name='menu blurb')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cities.city')),
            ],
        ),
    ]
