# Generated by Django 3.2.2 on 2021-10-30 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotspot',
            options={'ordering': ['ordinal']},
        ),
        migrations.AddField(
            model_name='hotspot',
            name='interactive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='interactives.interactive'),
        ),
    ]
