# Generated by Django 3.2.2 on 2021-11-03 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0002_auto_20211030_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractivePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=48, unique=True, verbose_name='short name')),
                ('part_num', models.IntegerField(default=99)),
                ('title', models.CharField(max_length=64)),
                ('interactive', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='interactives.interactive')),
            ],
        ),
    ]
