# Generated by Django 3.2.2 on 2021-11-03 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0003_interactivepart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotspot',
            name='interactive',
        ),
        migrations.AddField(
            model_name='hotspot',
            name='interactive_part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='interactives.interactivepart'),
        ),
    ]
