# Generated by Django 3.2.2 on 2022-01-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0005_auto_20211104_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotspot',
            options={'ordering': ['interactive_part', 'text_percent']},
        ),
        migrations.AlterModelOptions(
            name='interactivepart',
            options={'ordering': ['interactive', 'slug']},
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='hotspot_r',
            field=models.IntegerField(default=20, verbose_name='hotspot radius'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='text_percent',
            field=models.IntegerField(default=90, verbose_name='text position %'),
        ),
    ]
