# Generated by Django 3.2.2 on 2022-02-15 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0020_alter_archiveitem_source'),
        ('interactives', '0006_auto_20220104_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='archive_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspots', to='archive.archiveitem'),
        ),
        migrations.AddField(
            model_name='hotspot',
            name='slug',
            field=models.SlugField(blank=True, max_length=48, null=True, verbose_name='short name'),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='interactive_part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='hotspots', to='interactives.interactivepart'),
        ),
        migrations.AlterField(
            model_name='interactivepart',
            name='interactive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='interactiveParts', to='interactives.interactive'),
        ),
    ]
