# Generated by Django 3.2.2 on 2022-02-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactives', '0007_auto_20220215_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='zoom_percent',
            field=models.IntegerField(default=100),
        ),
    ]
