# Generated by Django 3.2.2 on 2021-06-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=48, unique=True, verbose_name='short name')),
                ('orig_filename', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_year', models.IntegerField(blank=True, null=True)),
                ('circa', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=128, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=128, null=True)),
                ('format', models.CharField(choices=[('photo', 'photo'), ('graph', 'graphic/ephemera'), ('draw', 'drawing'), ('map', 'map'), ('doc', 'document')], max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
