# Generated by Django 3.2.2 on 2021-06-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20210607_1746'),
        ('visuals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='persons',
            field=models.ManyToManyField(to='people.Person'),
        ),
    ]
