# Generated by Django 3.2.2 on 2021-07-04 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_district'),
        ('visuals', '0004_source_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='decade',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='priority',
            field=models.IntegerField(choices=[(0, '0 - Reference'), (1, '1 - Could Use'), (2, '2 - Pretty Good'), (3, '3 - Golden')], default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='status_num',
            field=models.IntegerField(choices=[(0, '0 - Initial Entry'), (1, '1 - In Admin Only'), (2, '2 - Development (Wireframe)'), (3, '3 - Candidate for Publication'), (4, '4 - Published')], default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='topics',
            field=models.ManyToManyField(blank=True, to='visuals.Topic'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='caption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='locations.location'),
        ),
    ]
