# Generated by Django 3.2.2 on 2021-07-04 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visuals', '0006_remove_image_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visuals.source'),
        ),
    ]
