# Generated by Django 3.2.2 on 2021-08-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visuals', '0008_auto_20210713_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='authored_by',
            field=models.CharField(choices=[('', '---'), ('Ann', 'Ann'), ('Dave', 'Dave'), ('Stacy', 'Stacy'), ('DG', 'DG')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
