# Generated by Django 3.2.2 on 2021-09-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20210713_1241'),
        ('people', '0004_auto_20210804_1245'),
        ('visuals', '0010_auto_20210923_1154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ArchiveItem',
        ),
    ]
