# Generated by Django 3.2.2 on 2021-08-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_options'),
        ('people', '0003_auto_20210704_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Primary Role'},
        ),
        migrations.AddField(
            model_name='person',
            name='cities',
            field=models.ManyToManyField(blank=True, to='cities.City'),
        ),
    ]
