# Generated by Django 3.2.2 on 2021-06-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('sub_title', models.CharField(blank=True, max_length=128, null=True)),
                ('grid_intro', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
