# Generated by Django 3.2.2 on 2021-06-09 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_devel', models.BooleanField(default=False, verbose_name='After Development')),
                ('title', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description for internal use')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city')),
            ],
        ),
    ]
