# Generated by Django 3.2.2 on 2021-07-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['city', 'after_devel', 'title']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['level', 'city']},
        ),
        migrations.AlterField(
            model_name='district',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes for internal use'),
        ),
    ]
