# Generated by Django 3.2.2 on 2021-10-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20210713_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['city', 'district'], 'verbose_name': 'District'},
        ),
    ]
