# Generated by Django 3.2.2 on 2021-10-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_location_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['city', 'district']},
        ),
    ]
