# Generated by Django 3.2.2 on 2022-03-18 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=1900)),
                ('blurb', models.CharField(max_length=194)),
                ('has_cell_image', models.BooleanField(default=False)),
                ('cell_image_ref', models.CharField(blank=True, max_length=128, null=True)),
                ('more_text', models.TextField(blank=True, null=True)),
                ('thrulines', models.ManyToManyField(blank=True, to='timeline.Thruline')),
                ('timeline_layer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='timelineEntries', to='timeline.timelinelayer')),
            ],
        ),
    ]
