# Generated by Django 3.2.2 on 2022-03-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_timelineentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineentry',
            name='blurb',
            field=models.TextField(),
        ),
    ]
