# Generated by Django 3.2.2 on 2022-03-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_alter_timelineentry_blurb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineentry',
            options={'ordering': ['timeline_layer', 'year']},
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='has_more',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='priority',
            field=models.IntegerField(choices=[(1, '1 - Maybe Not'), (2, '2 - Probably'), (3, '3 - For sure')], default=0),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='used_in',
            field=models.CharField(blank=True, help_text='e.g.: people/haines-dauner', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='timelineentry',
            name='used_in_title',
            field=models.CharField(blank=True, help_text='e.g.: Bob Haines and Gene Dauner, Photographers', max_length=128, null=True),
        ),
    ]
