# Generated by Django 3.2.2 on 2022-03-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_auto_20220320_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineentry',
            name='priority',
            field=models.IntegerField(choices=[(1, '1 - Probably Not'), (2, '2 - Maybe'), (3, '3 - For sure')], default=3),
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='used_in',
            field=models.CharField(blank=True, help_text='e.g.: people/haines-dauner', max_length=128, null=True, verbose_name='Link to'),
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='used_in_title',
            field=models.CharField(blank=True, help_text='e.g.: Bob Haines and Gene Dauner, Photographers', max_length=128, null=True, verbose_name='Link title'),
        ),
    ]
