# Generated by Django 3.2.2 on 2021-06-14 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_location_options'),
        ('people', '0002_auto_20210607_1746'),
        ('archive', '0002_image_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AlterField(
            model_name='image',
            name='persons',
            field=models.ManyToManyField(blank=True, to='people.Person'),
        ),
    ]
