# Generated by Django 3.2.2 on 2021-09-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_rename_image_archiveitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveitem',
            name='thumb_file',
            field=models.ImageField(default='placeholder.jpg', upload_to='visuals/thumbpics'),
        ),
    ]
