# Generated by Django 3.2.2 on 2021-09-23 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_alter_archiveitem_thumb_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='image', max_length=24, unique=True)),
                ('title', models.CharField(default='Image', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='photo', max_length=24, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('media_type', models.ForeignKey(default='image', on_delete=django.db.models.deletion.SET_DEFAULT, to='archive.mediatype')),
            ],
        ),
        migrations.AddField(
            model_name='archiveitem',
            name='media_format',
            field=models.ForeignKey(default='photo', on_delete=django.db.models.deletion.SET_DEFAULT, to='archive.mediaformat'),
        ),
    ]
