# Generated by Django 3.2.2 on 2021-09-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0012_alter_archiveitem_thumb_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='image', max_length=24, unique=True)),
                ('title', models.CharField(default='Image', max_length=32)),
            ],
        ),
    ]
