# Generated by Django 3.2.2 on 2021-09-23 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0013_mediatype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='photo', max_length=24, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('media_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='archive.mediatype')),
            ],
        ),
    ]
