# Generated by Django 3.2.2 on 2021-09-23 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0014_mediaformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveitem',
            name='media_format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='archive.mediaformat'),
        ),
    ]
