# Generated by Django 3.2.2 on 2021-10-22 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_alter_location_options'),
        ('archive', '0016_auto_20211022_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveitem',
            name='location',
        ),
        migrations.AddField(
            model_name='archiveitem',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.district'),
        ),
    ]
