# Generated by Django 3.2.2 on 2021-10-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0017_auto_20211022_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='caption'),
        ),
    ]
