# Generated by Django 3.2.2 on 2022-02-15 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0019_auto_20220206_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveitem',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archiveItems', to='archive.source'),
        ),
    ]
