# Generated by Django 3.2.2 on 2022-02-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0020_alter_archiveitem_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveitem',
            name='era',
            field=models.IntegerField(choices=[(0, 'Choose Era'), (1, '0 - 1940s'), (2, '1 - 1950s'), (3, '2 - 1960s'), (4, '3 - 1970s')], default=0),
        ),
    ]
