# Generated by Django 3.2.2 on 2022-03-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0021_archiveitem_era'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveitem',
            name='era',
        ),
        migrations.AddField(
            model_name='archiveitem',
            name='used_in',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='archiveitem',
            name='creation_year',
            field=models.IntegerField(default=1900, help_text='creation year', verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='archiveitem',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='archiveItems', to='archive.source'),
        ),
    ]
