# Generated by Django 3.2.2 on 2022-03-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0022_auto_20220315_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveitem',
            name='used_in_title',
            field=models.CharField(blank=True, help_text='e.g.: Bob Haines and Gene Dauner, Photographers', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='archiveitem',
            name='used_in',
            field=models.CharField(blank=True, help_text='e.g.: people/haines-dauner', max_length=64, null=True),
        ),
    ]
